add basic calculator UI
Reggeditt/math-magician pull request #2
Opened 2023-03-27 19:31 UTC by Reggeditt

- Created a new directory called components.
- Create a new Calculator.js file inside components.
- Created a React component that matches the wireframe design:
   > Calculator

- Implemented the design using only (JSX and CSS)

2023-03-27 20:04 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Reggeditt 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 20:04 UTC, tresorsawasawa commented on src/App.css
> -.App {
- [ ] AS required for the project, kindly make sure all the boilerplate that got created by the CRA (texts, images, and styles) are correctly deleted from your repo. Right now, I can see that all of them are still there such as `src/reportWebVitals.js`, `App.test.js`, `setupTests.js` files, `logo.svg`,...

2023-03-27 20:04 UTC, tresorsawasawa commented on src/componets/calculator.js
> +
- [ **OPTIONAL** ] For react nameable reasons, I think it would be better if you capitalize your Calculator component name file i.e. it should be named  `src/componets/Calculator.js` instead of `src/componets/calculator.js`

2023-03-27 20:04 UTC, tresorsawasawa commented on src/App.css
>  }
- [ ] `README.md` file: To make your documentation more descriptive and professional, I think it would be better if you update you `Getting Started` section by adding a command that helps users to access the cloned directory after cloning the repo and the one for running build for production before a user start the app. For example:  
```
 ...
  ### Setup
   Clone this repository to your desired folder:
   git clone https://github.com/Reggeditt/math-magician.git

### Install
Install this project with:
cd math-magician

npm install

npm run build

...
```

2023-03-27 20:04 UTC, tresorsawasawa commented on src/App.css
> +  margin: auto;
- [ ] Good job with your design. However, I noticed that your design is fixed at the top, there is no spacing at the top of your calculator. I suggest you margin at the top such as updating the `margin: auto;` to something similar to this: `margin: 6rem auto;`

2023-03-27 21:41 UTC, Reggeditt commented on src/App.css
> -.App {
Thanks for pointing it out.

2023-03-27 21:41 UTC, Reggeditt commented on src/App.css
> -.App {
fixed

2023-03-27 21:44 UTC, Reggeditt commented on src/App.css
>  }
fixed

2023-03-27 21:47 UTC, Reggeditt commented on src/componets/calculator.js
> +
fixed

2023-03-27 21:51 UTC, Reggeditt commented on src/App.css
> +  margin: auto;
fixed

2023-03-27 22:07 UTC, levy002 approved these changes
## Hello @Reggeditt 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly make sure to remove all comments in your README file in order to keep your repo clean and professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 22:08 UTC, merged

2023-05-29 08:09 UTC, Olamarx reviewed
Hi @Reggeditt, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/xT8qBepJQzUjXpeWU8/giphy.gif"/>
## Highlights
- Linters passed ✔️
- Readme file professional ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._